### ISSUE TITLE
Make this project fully independent of cappuccino-server

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-web#33]

**Comment by MattiaPrimavera** [comment]
Why did you find any dependance between the two of them?

**Comment by yvan-sraka** [comment]
I don't know how to launch `cappuccino-web` and set for example a remote `cappuccino-server` address?

**Comment by MattiaPrimavera** [comment]
`cappuccino-web` is served from the server when navigating to the address it tells you when running `cappuccino-server`

So why would you need that? It's like the `cappuccino-web` being a server feature ...
The server gives you a way of having access to your files via a web interface

**Comment by yvan-sraka** [comment]
To have something more clean : like the same API for web and android app, and do not have some **Django** template code syntax inside an **Angular JS** based project.. _gruik gruik :pig:!_

**Comment by yvan-sraka** [comment]
I think it could be cool to work with **NodeJS** in this project :) !

**Comment by yvan-sraka** [comment]
You need this issue done to make https://github.com/cappuccino-app/cappuccino-web/issues/24 and https://github.com/cappuccino-app/cappuccino-web/issues/24 !

**Comment by MattiaPrimavera** [comment]
Sorry mate, but there's actually no django code inside `cappuccino-web` as you can verify ... the template code comes from AngularJs ... the rest is javascript comunicating with the server through the API ... So there's actually no couplage btw the two of them but the API contract ...

**Comment by yvan-sraka** [comment]
Wow.. I'm so dub stupid, I hope I not disappointed you too much :disappointed_relieved:?
So hum hum.. Maybe a short **Setup** section in the `README.md` to explain how to launch the app to help me to test it :sweat_smile:!

**Comment by MattiaPrimavera** [comment]
ihih it's okay mate, even the best can be wrong sometimes :p
